# version is now removed since it's deprecated

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_ROOT_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: mydatabase
      MB_DB_PORT: 5432
      MB_DB_USER: myuser
      MB_DB_PASS: mypassword
      MB_DB_HOST: postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - my_network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: sqlite
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: securepass123
      N8N_HOST: n8n.local
      WEBHOOK_URL: http://localhost:5678
      N8N_RUNNERS_ENABLED: "true"
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_backups:/var/lib/pgadmin/storage/admin_admin.com

volumes:
  pgdata:
  pgadmin_data:

networks:
  my_network:
    driver: bridge
